version: '3'

services:
    miweb:
       container_name: directorioapp
       restart: always
       build: .
       ports:
          - "5000:3000"
       links: 
          - otromongo
       volumes:
          - .:/usr/app
          
    otromongo:
       container_name: mimongodatabase
       image: mongo 
       ports:
          - "27018:27017"
       logging:
           driver: none