version: "3"

services:
      miweb:
          container_name: proyecto
          restart: always
          build: .
          ports:
              - "4000:3000"
          links: 
              - mongo
          volumes:
              - .:/usr/src/app
      mongo:
          container_name: mongobasededatos
          image: mongo
          ports: 
              - "27017:27017"
          logging:
              driver: none